const API = import.meta.env.VITE_API_BASE_URL || "/api/v1";

export const endpoints = {
  auth: {
    login: `${API}/auth/login`,
    logout: `${API}/auth/logout`,
    refresh: `${API}/auth/refresh`,
    forgotPassword: `${API}/auth/forgot-password`,
    resetPassword: `${API}/auth/reset-password`,
    changePassword: `${API}/auth/change-password`,
    registerCounsellor: `${API}/auth/register-counsellor`,
    counsellors: `${API}/auth/counsellors`,
    counsellor: (userId: string) => `${API}/auth/counsellors/${userId}`,
  },
  branches: `${API}/branches`,
  branch: (id: string) => `${API}/branches/${id}`,
  branchSyncSeats: (id: string) => `${API}/branches/${id}/sync-seats`,
  students: `${API}/students`,
  student: (id: string) => `${API}/students/${id}`,
  studentSeat: (id: string) => `${API}/students/${id}/seat`,
  studentRegistrations: (id: string) => `${API}/students/${id}/registrations`,
  studentReceipts: `${API}/students/receipts`,
  studentReceipt: (studentId: string, receiptId: string) =>
    `${API}/students/${studentId}/receipts/${receiptId}`,
  studentReceiptRender: (studentId: string, receiptId: string) =>
    `${API}/students/${studentId}/receipts/${receiptId}/render`,
  plans: `${API}/plans`,
  plan: (id: string) => `${API}/plans/${id}`,
  planPricing: (id: string) => `${API}/plans/${id}/pricing`,
  planEffectivePricing: (id: string) => `${API}/plans/${id}/pricing/effective`,
  seats: `${API}/seats`,
  seatPlanBulkMap: `${API}/seats/plans/bulk-map`,
  seatAvailability: `${API}/seats/availability/live`,
  payments: `${API}/payments`,
  payment: (id: string) => `${API}/payments/${id}`,
  paymentSummary: (studentId: string) => `${API}/payments/students/${studentId}/summary`,
  renewals: `${API}/renewals`,
  renewal: (id: string) => `${API}/renewals/${id}`,
  renewalComplete: (id: string) => `${API}/renewals/${id}/complete`,
  renewalCancel: (id: string) => `${API}/renewals/${id}/cancel`,
  reports: {
    branchDashboard: `${API}/reports/branch/dashboard`,
    branchOccupancy: `${API}/reports/branch/occupancy`,
    branchRevenue: `${API}/reports/branch/revenue`,
    branchRenewalsDue: `${API}/reports/branch/renewals-due`,
    superDashboard: `${API}/reports/super/dashboard`,
    superComparison: `${API}/reports/super/comparison`,
    superPlanDistribution: `${API}/reports/super/plan-distribution`,
  },
  notifications: {
    list: `${API}/notifications`,
    center: `${API}/notifications/center`,
    unreadCount: `${API}/notifications/unread-count`,
    readAll: `${API}/notifications/read-all`,
    read: (id: string) => `${API}/notifications/${id}/read`,
    archive: (id: string) => `${API}/notifications/${id}/archive`,
  },
} as const;
